Here we will learn how we can use DataSet and Dataloader classes to implement the Mini Batch GD in our NN model

Dataset class has the responsibility to load the dataset from the memory

Dataloader class will make batches from the loaded data

__init__()-> tells how data should be loaded
__len__()-> which returns the total number of batches
__getitem__(index)-> returns the data at the given index

In [1]:
import torch

In [2]:
from sklearn.datasets import make_classification


In [5]:
## step 1-> create a synthetic classification dataset using sklearn
X, y= make_classification(

    n_samples = 10,
    n_features= 2,
    n_informative=2,
    n_redundant=0,
    n_classes= 2,
    random_state= 42
)

In [6]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [7]:
X.shape

(10, 2)

In [8]:
#convert numpy arrays to pytoch tensors

X= torch.tensor(X, dtype=torch.float32)
y= torch.tensor(y, dtype= torch.long)

In [9]:
from torch.utils.data import Dataset, DataLoader



In [12]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):

        self.features= features
        self.labels= labels
    
    def __len__(self):
        return self.features.shape[0]

    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [14]:
dataset= CustomDataset(X,y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[0]

tensor(1)

In [22]:
dataloader= DataLoader(dataset, batch_size=2, shuffle= True, num_workers= 2)

### Very important concept "collate_fn"
'''
the collate_fn is a function that specifies how to combine a list of samples from a dataset into a single batch. by default DataLoader uses a single batch collation mechanism but collate_fn allows you to customize how the data should be processed and batched
'''


## when shuffle is True then we are using random sampler to sample the data
## but if shufffle is false then the sampling is going to be sequential
# we can also make our custom samplers for sampling the data

'\nthe collate_fn is a function that specifies how to combine a list of samples from a dataset into a single batch. by default DataLoader uses a single batch collation mechanism but collate_fn allows you to customize how the data should be processed and batched\n'

In [21]:
for batch_features, batch_labels in dataloader:

    print(batch_features)
    print(batch_labels)

tensor([[-0.7206, -0.9606],
        [-1.9629, -0.9923]])
tensor([0, 0])
tensor([[1.8997, 0.8344],
        [1.7774, 1.5116]])
tensor([1, 1])
tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([1, 0])
tensor([[-0.9382, -0.5430],
        [ 1.7273, -1.1858]])
tensor([1, 1])
tensor([[-2.8954,  1.9769],
        [-1.1402, -0.8388]])
tensor([0, 0])


with above code you can only work sequentially to create batches but with multiple workers you can parallelise this batch making