In [ ]:
###Lets discuss core features of Pytorch
'''
1.Tensor computation 
  pytorch can represent any dimensional data 
2.gpu acceleration
3. automatic differentiation
   with autograd in pytorch we can easily perform differentiation during backpropagation
4. distributed training
5. interpretability with libraries
  
'''


In [ ]:
'''
Tensors 

Tensor is a multi-dimesional array designed for mathematical and computational efficiency



=> Tensors are optimized for hardware acceleration, allowing computation on GPUs or TPUs which are crucial for training deep learning models

'''

In [ ]:
''''
Where do we use tensors in DL:

Data Storage
Weights and biases
matrix  operations 
training process

'''

In [24]:
import torch


In [154]:
print(torch.__version__)

2.14.0+cpu


In [155]:
if torch.cuda.is_available():
    print('GPU is available')
else:
    print('GPU is not available')

GPU is not available


In [ ]:
### creating tensors

a= torch.empty(2,3)
print(a)
print(type(a))

tensor([[6.2140e-33, 8.5619e-43, 8.1571e-01],
        [5.7864e-01, 8.8395e-01, 7.4881e-03]])
<class 'torch.Tensor'>


In [12]:
##using zeroes

a= torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
##using Ones
b= torch.ones(2,4, dtype=int)
b

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [17]:
##with random

c= torch.rand(2,3)

print(c)

tensor([[0.4670, 0.4367, 0.1232],
        [0.7502, 0.7696, 0.2610]])


In [21]:
## we can also provide our own values to make them as tensor

c= torch.tensor([[1,2,3],[4,5,6]])

print(c)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [157]:
a= torch.arange(0,10)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [35]:
a= torch.linspace(0,10,5, dtype=int)
print(a)

tensor([ 0,  2,  5,  7, 10])


In [36]:
##Torch Tensors

print(a.shape)

torch.Size([5])


In [158]:
#make a tensor of same shape but empty
v= torch.empty_like(a)
print(v)

x= torch.zeros_like(a)

print(x)

y= torch.ones_like(a)

print(y)

torch.rand_like(a, dtype=float)

u=torch.randint_like(a, low=0, high=10, dtype=torch.int64)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [65]:
##Mathematical operations in pytorch

a= torch.arange(10)
c= a+2
print(a)
print(c)

d= a//2
print(d)

e= a**2
print(e)


## using tensor to tensor operations

a= torch.empty(2,3)
a=a*100
b= torch.ones(2,3)
print(a+b)

d= a-b
print(d)

e= a*b

print(e)

f= a//b
print(f)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])
tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])
tensor([[101., 101., 101.],
        [101., 101., 101.]])
tensor([[99., 99., 99.],
        [99., 99., 99.]])
tensor([[100., 100., 100.],
        [100., 100., 100.]])
tensor([[100., 100., 100.],
        [100., 100., 100.]])


In [68]:
##tensor of given size

a= torch.randint(size=(2,3),low=0, high=20)

print(a)

tensor([[ 4,  9, 18],
        [18, 14,  4]])


In [165]:
##sum of whole tensor

s= torch.sum(a)
print(s)

## row wise sum
a= torch.rand(2,6)*100

print(a)
s= torch.sum(a,dim=0)
print(s)

##column wise sum

s= torch.sum(a, dim=1)
print(s)

##Product 
print(torch.prod(a))

tensor(415.1474)
tensor([[59.2998, 85.4166, 21.4356, 75.3696, 55.8158, 91.8287],
        [32.2208, 24.8675, 14.7439, 81.0341, 96.5608, 99.3899]])
tensor([ 91.5206, 110.2841,  36.1796, 156.4036, 152.3766, 191.2186])
tensor([389.1661, 348.8170])
tensor(3.8535e+20)


In [91]:
##Mean, median and mode
a = torch.tensor([[1.0, 2.5, 3.0], 
                  [4.2, 5.0, 6.1]], dtype=torch.float32)

a= torch.rand(2,3)
## column mean
print(torch.mean(a,dim=1))

##row mean
print(torch.mean(a, dim=0))

tensor([0.5355, 0.2135])
tensor([0.4391, 0.2884, 0.3960])


In [ ]:
maxi= torch.max(a)
print(maxi)
mini= torch.min(a)
print(mini)
##below tells index of max element
print(torch.argmax(a))

print(torch.argmin(a))


tensor(0.6583)
tensor(0.1337)
tensor(2)
tensor(5)


In [99]:
##Matrix multiplication
a=torch.rand(3,4)
b=torch.rand(4,3)

c= torch.matmul(a,b)

In [ ]:
## transpose
a= torch.rand(3,4)

print(a)
b= torch.transpose(a,0,1)
print(a)
print(b)


tensor([[0.5499, 0.4330, 0.8352, 0.9185],
        [0.1306, 0.6426, 0.8346, 0.4101],
        [0.5988, 0.5649, 0.5728, 0.0420]])
tensor([[0.5499, 0.4330, 0.8352, 0.9185],
        [0.1306, 0.6426, 0.8346, 0.4101],
        [0.5988, 0.5649, 0.5728, 0.0420]])
tensor([[0.5499, 0.1306, 0.5988],
        [0.4330, 0.6426, 0.5649],
        [0.8352, 0.8346, 0.5728],
        [0.9185, 0.4101, 0.0420]])


In [109]:
##Determinent
a= torch.rand(4,4)
c= torch.det(a)
print(c)

tensor(0.1715)


In [111]:
##comparison operatins
a= torch.rand(2,3)
b=torch.rand(2,3)
print(a>b)

tensor([[False,  True,  True],
        [ True, False,  True]])


In [113]:
## sqrt

v= torch.sqrt(a)
print(v)

tensor([[0.6501, 0.8352, 0.8774],
        [0.8354, 0.4552, 0.7744]])


In [120]:
a= torch.ones(3,4)

print(torch.sigmoid(a))
print(torch.softmax(a, dim=1))

print(torch.relu(a))

tensor([[0.7311, 0.7311, 0.7311, 0.7311],
        [0.7311, 0.7311, 0.7311, 0.7311],
        [0.7311, 0.7311, 0.7311, 0.7311]])
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
##in-place opertions
##changing original tensors

a= torch.rand(10,10)
b= torch.rand(10,10)

a.add_(b)

print(a)


torch.Size([10, 10])


In [ ]:
print(a)
a.relu_()
print(a)


tensor([[0.9910, 0.7493, 1.3096, 0.6376, 0.5783, 0.8533, 1.4974, 0.8964, 1.6626,
         1.0398],
        [0.3557, 0.6628, 0.5060, 0.7766, 0.7616, 1.8708, 1.4319, 1.9159, 0.7934,
         1.0716],
        [0.7467, 1.3107, 0.7583, 0.8125, 0.9316, 1.1022, 1.6985, 1.0869, 0.5485,
         1.1878],
        [1.0119, 0.3936, 1.3971, 0.7127, 1.7765, 0.5412, 0.8465, 1.4557, 1.6825,
         1.2029],
        [1.0517, 0.7939, 1.8476, 1.6828, 1.0742, 0.3978, 1.6977, 0.5209, 1.0292,
         1.1554],
        [1.5198, 0.4599, 1.1002, 0.6885, 1.3000, 1.1845, 1.1520, 1.1189, 1.6932,
         0.7828],
        [0.7509, 1.1346, 1.0160, 0.7932, 1.7482, 0.5406, 0.6428, 1.8128, 1.4114,
         0.4676],
        [1.0510, 0.4022, 1.5526, 0.2816, 0.7655, 1.3037, 0.7783, 1.0295, 0.5799,
         1.9127],
        [1.1069, 0.8345, 0.4353, 1.1502, 1.3516, 1.4222, 0.7694, 1.6374, 1.6553,
         0.7810],
        [0.7833, 1.3225, 1.2533, 1.0557, 1.3410, 1.4539, 1.8772, 0.9901, 0.8545,
         0.9273]])
tensor([[

In [ ]:
###copying a tensor

##shallow copy
a= torch.rand(2,3)
b=a

##Deep copy
c= a.clone()
c[0][0]=1
print(c)
print("original was below")
print(a)




tensor([[1.0000, 0.6718, 0.8157],
        [0.5786, 0.8839, 0.0075]])
original was below
tensor([[0.4043, 0.6718, 0.8157],
        [0.5786, 0.8839, 0.0075]])


AttributeError: 'Tensor' object has no attribute 'prod_'

In [ ]:
##Reshape
a= torch.rand(10,10)

print(a)
a.reshape(10,2,5)

##does not modifies the original tensor gives a new tensor
print(a)

tensor([[0.9662, 0.9670, 0.6809, 0.0611, 0.2220, 0.0738, 0.7897, 0.1483, 0.4296,
         0.0903],
        [0.7974, 0.3490, 0.7299, 0.4728, 0.9958, 0.1980, 0.6217, 0.8220, 0.6804,
         0.8848],
        [0.2533, 0.0776, 0.1565, 0.4287, 0.5910, 0.2440, 0.7498, 0.4815, 0.1450,
         0.0957],
        [0.7022, 0.3126, 0.9382, 0.9020, 0.0277, 0.3050, 0.8391, 0.8368, 0.2438,
         0.9511],
        [0.2330, 0.2478, 0.7182, 0.0051, 0.8324, 0.3285, 0.7323, 0.1497, 0.3216,
         0.2787],
        [0.2514, 0.3117, 0.7017, 0.8642, 0.0422, 0.0729, 0.4965, 0.4034, 0.2708,
         0.0090],
        [0.9199, 0.0384, 0.2895, 0.0322, 0.2458, 0.2941, 0.7869, 0.9200, 0.8124,
         0.5540],
        [0.4333, 0.1850, 0.9066, 0.4031, 0.2314, 0.6394, 0.3691, 0.6624, 0.4788,
         0.1204],
        [0.6325, 0.0261, 0.8399, 0.0612, 0.1145, 0.6120, 0.7788, 0.5525, 0.8510,
         0.1858],
        [0.2558, 0.9722, 0.1826, 0.1057, 0.9041, 0.2244, 0.8630, 0.4049, 0.2331,
         0.9353]])


AttributeError: 'Tensor' object has no attribute 'reshape_'

In [142]:
b=a.flatten()
print(a)
print(b)


tensor([[0.9662, 0.9670, 0.6809, 0.0611, 0.2220, 0.0738, 0.7897, 0.1483, 0.4296,
         0.0903],
        [0.7974, 0.3490, 0.7299, 0.4728, 0.9958, 0.1980, 0.6217, 0.8220, 0.6804,
         0.8848],
        [0.2533, 0.0776, 0.1565, 0.4287, 0.5910, 0.2440, 0.7498, 0.4815, 0.1450,
         0.0957],
        [0.7022, 0.3126, 0.9382, 0.9020, 0.0277, 0.3050, 0.8391, 0.8368, 0.2438,
         0.9511],
        [0.2330, 0.2478, 0.7182, 0.0051, 0.8324, 0.3285, 0.7323, 0.1497, 0.3216,
         0.2787],
        [0.2514, 0.3117, 0.7017, 0.8642, 0.0422, 0.0729, 0.4965, 0.4034, 0.2708,
         0.0090],
        [0.9199, 0.0384, 0.2895, 0.0322, 0.2458, 0.2941, 0.7869, 0.9200, 0.8124,
         0.5540],
        [0.4333, 0.1850, 0.9066, 0.4031, 0.2314, 0.6394, 0.3691, 0.6624, 0.4788,
         0.1204],
        [0.6325, 0.0261, 0.8399, 0.0612, 0.1145, 0.6120, 0.7788, 0.5525, 0.8510,
         0.1858],
        [0.2558, 0.9722, 0.1826, 0.1057, 0.9041, 0.2244, 0.8630, 0.4049, 0.2331,
         0.9353]])
tensor([0

In [144]:
a= torch.rand(2,3,4)
a.permute(2,1,0)

tensor([[[0.0325, 0.2118],
         [0.2176, 0.2487],
         [0.3710, 0.0537]],

        [[0.5249, 0.5096],
         [0.2677, 0.6895],
         [0.4328, 0.4820]],

        [[0.4633, 0.0378],
         [0.9577, 0.4726],
         [0.5518, 0.4280]],

        [[0.7130, 0.4092],
         [0.0128, 0.4941],
         [0.6352, 0.6150]]])

In [147]:
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1,226,226,3])

a.squeeze(0)

tensor([[[0.0325, 0.5249, 0.4633, 0.7130],
         [0.2176, 0.2677, 0.9577, 0.0128],
         [0.3710, 0.4328, 0.5518, 0.6352]],

        [[0.2118, 0.5096, 0.0378, 0.4092],
         [0.2487, 0.6895, 0.4726, 0.4941],
         [0.0537, 0.4820, 0.4280, 0.6150]]])

In [153]:
##numpy arrays to tensor
import numpy as np
a=torch.tensor([1,2,3])
b= np.arange(1,4)


c= torch.from_numpy(b)
print(c)

tensor([1, 2, 3])


In [5]:

import torch
x= torch.arange(10)
print(x)

torch.clamp(x, min=2, max=8)
print(x)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
