We will learn NN module of PyTorch


We will learn how to build a simple neural network pipeline
and we have the NN module that provides the built in functions for activation loss and other


In [2]:
import pandas as pd
import torch 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
print(df.head())
print(df.iloc[:,1:])



         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

In [ ]:
'''
Code flow

1. load the dataset
2. basic programming
3. training process
   a. create the model
   b. forward pass
   c. back propagation
   d. parameters update
4. Model Evaluation


'''

In [8]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)



In [9]:
print(df.iloc[:,0])

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object


In [11]:
df.iloc[:,1:]

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


Train Test Split

In [12]:
X_train, X_test, y_train, y_test= train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

Scaling

In [14]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

Label encoding

In [15]:
encoder= LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)

In [ ]:
y_test

Numpy arrays to PyTorch tensors

In [16]:
X_train_tensor= torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor= torch.from_numpy(y_train)
y_test_tensor= torch.from_numpy(y_test)

In [ ]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float().reshape(-1,1)

model = MySimpleNN(X_train_tensor.shape[1])

In [26]:
X_train_tensor

tensor([[-0.1032,  0.7038, -0.0550,  ...,  0.8244,  0.3186,  0.5774],
        [ 0.0159,  1.0667,  0.0373,  ...,  0.9743,  2.9533,  1.1019],
        [ 1.6085,  0.6703,  1.5675,  ...,  1.9069, -0.1814, -0.3946],
        ...,
        [ 1.3988,  1.3055,  1.4974,  ...,  2.0658,  2.8668,  1.1698],
        [ 2.2320,  0.6106,  2.2763,  ...,  1.9735, -0.2246,  0.1480],
        [-0.6189, -1.0466, -0.6073,  ..., -0.9869,  0.3892, -0.4088]],
       dtype=torch.float64)

Define the Model

In [ ]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.linear= nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    
    def forward(self,num_features):
        out= self.linear(num_features)
        out= self.sigmoid(out)

        return out
    
    # def loss_function(self, y_pred, y):
    # # Clamp predictions to avoid log(0)
    #    epsilon = 1e-7
    #    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    #in place of ths loss function we will use the built in loss function

    # Calculate loss
       loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
       return loss

In [48]:
##using built in loss function

loss_function= nn.BCELoss()

Important parameters

In [38]:
learning_rate= 0.1
epochs=25

In [19]:
X_train_tensor.shape[1]

30

Training Pipeline

In [54]:
#Create Model

model= MySimpleNN(X_train_tensor.shape[1])


###define optimizers
optimizer= torch.optim.SGD(model.parameters(),
lr=learning_rate)


# define loop
for epoch in range(epochs):
  #forward pass
  y_pred= model(X_train_tensor)

  # loss calucation
  loss= loss_function(y_pred,y_train_tensor)
  
  # backpropagation
  
  loss.backward()
  
  optimizer.zero_grad()
  #parameters update
  # with torch.no_grad():
  #   model.linear.weight-=learning_rate*model.linear.weight.grad
  #   model.linear.bias-=learning_rate*model.linear.bias.grad

  ##now we will use optim to do the parameter updates 
  optimizer.step()
  #zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  ## this above can also be done with one line


  #print loss in each epoch
  print(f"epoch: {epoch+1}, Loss: {loss.item()}")


epoch: 1, Loss: 0.6169257760047913
epoch: 2, Loss: 0.6169257760047913
epoch: 3, Loss: 0.6169257760047913
epoch: 4, Loss: 0.6169257760047913
epoch: 5, Loss: 0.6169257760047913
epoch: 6, Loss: 0.6169257760047913
epoch: 7, Loss: 0.6169257760047913
epoch: 8, Loss: 0.6169257760047913
epoch: 9, Loss: 0.6169257760047913
epoch: 10, Loss: 0.6169257760047913
epoch: 11, Loss: 0.6169257760047913
epoch: 12, Loss: 0.6169257760047913
epoch: 13, Loss: 0.6169257760047913
epoch: 14, Loss: 0.6169257760047913
epoch: 15, Loss: 0.6169257760047913
epoch: 16, Loss: 0.6169257760047913
epoch: 17, Loss: 0.6169257760047913
epoch: 18, Loss: 0.6169257760047913
epoch: 19, Loss: 0.6169257760047913
epoch: 20, Loss: 0.6169257760047913
epoch: 21, Loss: 0.6169257760047913
epoch: 22, Loss: 0.6169257760047913
epoch: 23, Loss: 0.6169257760047913
epoch: 24, Loss: 0.6169257760047913
epoch: 25, Loss: 0.6169257760047913


In [46]:
model.linear.weight

Parameter containing:
tensor([[ 0.0929, -0.1158,  0.0288,  0.0336, -0.0743, -0.1499, -0.1355,  0.1411,
         -0.0540, -0.0170, -0.1599, -0.0903, -0.1279,  0.1056,  0.1697,  0.0056,
         -0.0867, -0.0316,  0.1442,  0.1183, -0.0396,  0.0938,  0.0907,  0.0112,
         -0.0549,  0.0552,  0.0245,  0.0977, -0.1130,  0.1621]],
       requires_grad=True)

Evaluation


In [ ]:
#Model Evaluation
with torch.no_grad():
    y_pred= model.forward(X_test_tensor)
    y_pred= (y_pred>0.5).float()
    accuracy= (y_pred== y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")
print(y_pred)

In [13]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [14]:
features= torch.rand(10,5)

#crete model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4250],
        [0.4146],
        [0.4563],
        [0.4082],
        [0.5462],
        [0.3536],
        [0.4762],
        [0.4784],
        [0.5049],
        [0.4338]], grad_fn=<SigmoidBackward0>)

In [17]:
model.linear.weight

Parameter containing:
tensor([[-0.0838,  0.4214,  0.4421, -0.0353, -0.3623]], requires_grad=True)

In [47]:
model.linear.bias

Parameter containing:
tensor([-0.1603], requires_grad=True)