In [1]:
'''
Now we will create a NN with 5 inputs and one hidden layer with 3 neurons 
so there will be 18 weights and 4 biases in our network

'''

'\nNow we will create a NN with 5 inputs and one hidden layer with 3 neurons \nso there will be 18 weights and 4 biases in our network\n\n'

In [2]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2= nn.Linear(3,1)
        self.sigmoid= nn.Sigmoid()

    def forward(self, features):

        out = self.linear1(features)
        out= self.relu(out)
        out= self.linear2(out)
        out = self.sigmoid(out)

        return out

In [3]:
features= torch.rand(10,5)

#crete model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.3331],
        [0.3431],
        [0.3099],
        [0.3539],
        [0.3874],
        [0.3226],
        [0.3474],
        [0.3585],
        [0.3326],
        [0.3655]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear1.bias

Parameter containing:
tensor([ 0.3153,  0.4276, -0.0406], requires_grad=True)

In [5]:

## Now we will use the Sequential container to 

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        # self.linear1 = nn.Linear(num_features, 3)
        # self.relu = nn.ReLU()
        # self.linear2= nn.Linear(3,1)
        # self.sigmoid= nn.Sigmoid()

        self.network= nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        # out = self.linear1(features)
        # out= self.relu(out)
        # out= self.linear2(out)
        # out = self.sigmoid(out)

        out= self.network(features)

        return out

In [6]:
features= torch.rand(10,5)

#crete model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4172],
        [0.4238],
        [0.4230],
        [0.4219],
        [0.4178],
        [0.4186],
        [0.4210],
        [0.4205],
        [0.4199],
        [0.4220]], grad_fn=<SigmoidBackward0>)