Numpy Tricks 

In [13]:
import numpy as np

a= np.arange(10)
np.sort(a)
b= np.random.randint(1,100,15).reshape(5,3)

c=np.sort(b, axis=0)[::-1]
print(c)


[[91 76 69]
 [74 61 59]
 [25 35 58]
 [16 32 21]
 [ 6 17 16]]


In [16]:
a=np.arange(100)
c=np.append(a,200)
print(a)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 200]


In [21]:
d= np.append(b,np.ones((b.shape[0],1)), axis=1)
print(b)
print(d)

[[91 76 21]
 [16 35 69]
 [74 17 59]
 [25 32 58]
 [ 6 61 16]]
[[91. 76. 21.  1.]
 [16. 35. 69.  1.]
 [74. 17. 59.  1.]
 [25. 32. 58.  1.]
 [ 6. 61. 16.  1.]]


In [25]:
## concatenate

a= np.arange(12).reshape(3,4)
b= np.arange(12).reshape(3,4)

c= np.concatenate((a,b),axis=0)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
a= np.arange(12).reshape(3,4)
b= np.arange(15).reshape(3,5)
## row-wise concatenation below
np.concatenate((a,b), axis=1)
## column wise concatenation 
a= np.arange(12).reshape(3,4)
b=np.arange(20).reshape(5,4)

c= np.concatenate((a,b),axis=0)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [33]:
## unique function

a=np.array([1,2,3,4,4,54,34])
c= np.unique(a)
print(c)

##for 2-D arrays
b= np.arange(12).reshape(3,4)
c= np.unique(b)
print(c)



[ 1  2  3  4 34 54]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
##np.expand_dims
#1-d=>2-D
a=np.arange(12)


## in numpy 0=>rows and 1=>columns
c=np.expand_dims(a,axis=1)
print(c)


[0]


In [44]:
## Where

c= np.where(a>10)
print(c)
d= np.where(a%2==0)
print(d)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49]),)
(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48]),)


In [54]:

##  find all the indices with value greater than 50
a= np.arange(100).reshape(10,10)
c= np.where(a>50)
print(c)
print(np.shape(c))


(array([5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2,
       3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4,
       5, 6, 7, 8, 9]))
(2, 49)


In [56]:
## replace all values >50 with 0

np.where(a>50,0,a)

## replace evens with 0

np.where(a%2==0, 0, a)

array([[ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9],
       [ 0, 11,  0, 13,  0, 15,  0, 17,  0, 19],
       [ 0, 21,  0, 23,  0, 25,  0, 27,  0, 29],
       [ 0, 31,  0, 33,  0, 35,  0, 37,  0, 39],
       [ 0, 41,  0, 43,  0, 45,  0, 47,  0, 49],
       [ 0, 51,  0, 53,  0, 55,  0, 57,  0, 59],
       [ 0, 61,  0, 63,  0, 65,  0, 67,  0, 69],
       [ 0, 71,  0, 73,  0, 75,  0, 77,  0, 79],
       [ 0, 81,  0, 83,  0, 85,  0, 87,  0, 89],
       [ 0, 91,  0, 93,  0, 95,  0, 97,  0, 99]])

In [85]:
## argmax

## return the indices of the max element of the array in a particular axis
a= np.arange(100)
a[99]=1
a[98]=99
print(np.argmax(a))
print(a[np.argmax(a)])


a= np.arange(50).reshape(5,10)
print(a)
np.argmax(a, axis=0)#column wise max
np.argmax(a, axis=1)#columns wise max
 

 ## we also have argmin

print(np.argmin(a))



98
99
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
0


In [90]:
np.cumsum(a)
print(a)
np.cumsum(a, axis=0)
np.cumsum(a, axis=1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([[  0,   1,   3,   6,  10,  15,  21,  28,  36,  45],
       [ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145],
       [ 20,  41,  63,  86, 110, 135, 161, 188, 216, 245],
       [ 30,  61,  93, 126, 160, 195, 231, 268, 306, 345],
       [ 40,  81, 123, 166, 210, 255, 301, 348, 396, 445]])

In [88]:
np.cumprod(a)
np.cumprod(a, axis=1)

array([[                0,                 0,                 0,
                        0,                 0,                 0,
                        0,                 0,                 0,
                        0],
       [               10,               110,              1320,
                    17160,            240240,           3603600,
                 57657600,         980179200,       17643225600,
             335221286400],
       [               20,               420,              9240,
                   212520,           5100480,         127512000,
               3315312000,       89513424000,     2506375872000,
           72684900288000],
       [               30,               930,             29760,
                   982080,          33390720,        1168675200,
              42072307200,     1556675366400,    59153663923200,
         2306992893004800],
       [               40,              1640,             68880,
                  2961840,         13032096

In [92]:
np.percentile(a, 50)

np.float64(24.5)

In [ ]:


np.histogram(a, bins=10)

(array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]),
 array([ 0. ,  4.9,  9.8, 14.7, 19.6, 24.5, 29.4, 34.3, 39.2, 44.1, 49. ]))

In [ ]:

a= np.arange(10)
b= np.random.randint(1,20,10)
np.corrcoef(a,b)

#  a b
# a
# b


array([[1.     , 0.12183],
       [0.12183, 1.     ]])

In [102]:
## np.isin

items= [1,20,30, 40,50,60, 70,80,90]
np.isin(a,items)

a[np.isin(a,items)]

array([1])

In [107]:
np.flip(a)
# reverses the array preserving the shape of the array

b= np.arange(100).reshape(10,10)
np.flip(b, axis=0) ## column wise
np.flip(b)## row wise + column wise 
np.flip(b, axis=1) # row wise


array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [113]:

a= np.arange(10)
b= np.delete(a,[0,2])
print(b)

[1 3 4 5 6 7 8 9]


In [116]:
### set functions

np.union1d(a,b)
np.intersect1d(a,b)
np.setdiff1d(a,b)
np.setxor1d(a,b)
np.in1d(a,b)

C:\Users\aksha\AppData\Local\Temp\ipykernel_21224\1971109808.py:7: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,b)


array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True])