In [5]:
import numpy as np

a= np.array([1,2,3])
print(a)

b=np.array([1,2,3,4], dtype= 'str')
c=np.array([1,2,3,4,5], dtype='float')
print(c)
print(b)

[1 2 3]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4']


In [8]:
d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [ ]:
e= np.arange(1,11).reshape(2,5)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
g=np.ones(3)
g

array([1., 1., 1.])

In [18]:
f= np.zeros(2)
f[0]=1
print(f)

[1. 0.]


In [23]:
a= np.random.random((3,4))
print(a)

[[0.33082349 0.05192166 0.37782877 0.05831727]
 [0.40674117 0.84281684 0.82927316 0.31792745]
 [0.38174741 0.68377455 0.61794413 0.48899047]]


In [24]:
d= np.linspace(-10,10,10)
print(d)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [29]:
f=np.identity(2, dtype= 'int')
print(type(f))
print(f)

<class 'numpy.ndarray'>
[[1 0]
 [0 1]]


In [41]:
a=np.arange(10)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
b= np.arange(10, dtype='int').reshape((2,5))
print(b)
print(b.size)
print(b.shape)
print(b.ndim)
c=np.arange(16).reshape(2,2,2,2)
print(c)
print(c.size)
print(c.shape)
print(c.ndim)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)
10
[[0 1 2 3 4]
 [5 6 7 8 9]]
10
(2, 5)
2
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
16
(2, 2, 2, 2)
4


In [45]:
a.itemsize

a.itemsize

8

In [54]:
age= np.arange(90, dtype='float')
age.dtype

dtype('float64')

In [62]:
a= np.arange(12).reshape(3,4)
b=np.arange(12,24).reshape(3,4)

a*2
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [66]:
fg= a>5
print(fg)
print(a)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [74]:
x=np.arange(10,)
y=np.arange(10)
print(x+y)
z=x+y
x=x+y
print(x+2)

[ 0  2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
## array functions
x=np.random.random((3,3))
x=np.round(x*100)
x

array([[63., 89., 78.],
       [60., 83., 47.],
       [89.,  8., 50.]])

In [85]:
print(np.max(x))
print(np.min(x))
#row and column wise min max
print(np.max(x,axis=1)) #0-col
print(np.min(x,axis=0))# 1- row

## sum and product
print(np.sum(x))
print(np.prod(x))

89.0
8.0
[89. 83. 89.]
[60.  8. 47.]
567.0
3644201289456000.0


In [ ]:
## statistics 

print(np.mean(x))


63.0


In [97]:
#dot product

x= np.arange(10).reshape(2,5)
y= np.arange(10).reshape(5,2)
print(np.dot(x,y))
z=np.dot(x,y)
print(z[1,0])

f= np.arange(30).reshape(3,2,5)
print(f)
print(f[0,1,4])


[[ 60  70]
 [160 195]]
160
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
9


In [107]:
a=np.arange(12).reshape(3,4)
print(a[1,::3])
print(a)
print(a[::2,1::2])

[4 7]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  3]
 [ 9 11]]


In [128]:
a=np.arange(27).reshape(3,3,3)
print(a)
# print(a[1,2,1])
# print(a[0,1,:])
# print(a[1,:,1])

print(a[::2,0,::2])



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 0  2]
 [18 20]]


In [137]:

ls=[]
for i in np.nditer(a):
    x=i
    ls.append(x)
    

print(ls[::])


[array(0), array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11), array(12), array(13), array(14), array(15), array(16), array(17), array(18), array(19), array(20), array(21), array(22), array(23), array(24), array(25), array(26)]


In [141]:
print(np.transpose(a))


[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [143]:
print(np.ravel(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [151]:
x=np.arange(12).reshape(3,4)
y= np.arange(12,24).reshape(3,4)

np.hstack((x,y))
np.vstack((x,y))

np.hsplit(x,2)

g=np.arange(12).reshape(2,6)
np.vsplit(g,2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]