Numpy arrays vs Python lists

In [1]:
import numpy as np


In [5]:
#normal indexing 

a= np.arange(12).reshape(3,4)

print(a)

print(a[1::,1::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  7]
 [ 9 11]]


In [12]:
##fancy indexing

a= np.arange(24).reshape(6,4)
print(a)
# for rows 
print(a[[0,2, 5,4]])
print(a[[0,2,4]])
#for columns 
print(a[:,[0,1,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [20 21 22 23]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]
 [12 13 15]
 [16 17 19]
 [20 21 23]]


In [ ]:
#boolean indexing
##generates 24 random integers between 1 to 100
a= np.random.randint(1,100,24).reshape(6,4)
print(a)

[[71 77 89 83]
 [50 17 86 48]
 [47 87 59 66]
 [45 70 44 49]
 [43 97 32 96]
 [ 2 46 10  4]]


In [21]:
#print all the numbers greater than 50
print(a>50)
res_array_1d=a[a>0]
print(res_array_1d)
#numbers greater than 50 and also even
a[(a>50) & (a%2==0)]
#numbers not divisible by 7

print(a[~(a%7==0)])

[[ True  True  True  True]
 [False False  True False]
 [False  True  True  True]
 [False  True False False]
 [False  True False  True]
 [False False False False]]
[71 77 89 83 50 17 86 48 47 87 59 66 45 70 44 49 43 97 32 96  2 46 10  4]
[71 89 83 50 17 86 48 47 87 59 66 45 44 43 97 32 96  2 46 10  4]


Broadcasting in numpy


In [ ]:
a=np.arange(6).reshape(2,3)
b= np.arange(3)
print(a+b)








ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [25]:
a= np.arange(16).reshape(4,4)
b= np.arange(4).reshape(2,2)

print(a+b)


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

(4, 3)(3,)4, 3   3✅ YES3 matches 3. The empty space acts like a 1.(4, 3)(4, 1)4, 34, 1✅ YES4 matches 4. The 1 stretches to match 3.(4, 4)(2, 2)4, 42, 2❌ NO4 and 2 do not match, and neither is 1.

The Mental Shortcut: "The Rubber Band Rule"Think of the number 1 as a rubber band.If a dimension is 1, NumPy can stretch it to any number to match the other array.If a dimension is missing (empty space on the left), NumPy automatically treats it as a 1 and stretches it.If a dimension is 2, 3, 4, etc., it is frozen. It cannot be stretched to match a different frozen number.


Working with mathematics

In [27]:
a= np.arange(10)
print(np.sum(a))
print(np.sin(a))

45
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [30]:
##sigmoid

def sigmoid(array):
    return 1/(1+np.exp(array))


a=np.arange(10)
b=sigmoid(a)
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[5.00000000e-01 2.68941421e-01 1.19202922e-01 4.74258732e-02
 1.79862100e-02 6.69285092e-03 2.47262316e-03 9.11051194e-04
 3.35350130e-04 1.23394576e-04]


In [32]:
#mean squared error

actual= np.random.randint(1,50,25)
predicted= np.random.randint(1,50,25)

#mse
def MSE(actual, predicted):
  return np.mean( (actual-predicted)**2)


MSE(actual, predicted)

np.float64(468.88)

In [33]:
#binary cross entropy

np.mean((actual-predicted)**2)

np.float64(468.88)

In [ ]:
##working with missing values

a=np.array([1,2,3,np.nan,5])
print(a)

#finding missing values
a[~np.isnan(a)]


ValueError: cannot convert float NaN to integer

In [48]:

import matplotlib.pyplot as plt
##plotting graphs

x=np.linspace(-10,10,100)
y=x
print(x)
plt.plot(x,y)

ModuleNotFoundError: No module named 'matplotlib.backends.registry'